---
name: check_shell_scripts

'on':
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  run_shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Install shellcheck
        run: |
          sudo apt-get install shellcheck

      - name: display shellcheck version
        run: |
          shellcheck --version

      - name: run check_shell_scripts
        run: |
          ./check_shell_scripts.sh
...
