---
name: latex_linter_check

'on':
  workflow_dispatch:
  push:
    paths-ignore:
      - 'generated/**'

permissions:
  contents: read

jobs:
  run_chktex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: LaTeX linter
        uses: colinaaa/chktex-action@5dda098b973d69cdc61ace93fa7bfcef39efaade # v1.1.2
...
